# Generated by Django 5.2 on 2025-04-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frase',
            name='metodos',
        ),
        migrations.AlterField(
            model_name='frase',
            name='categoriaFrase',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='frase',
            name='modelo_laudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.modelolaudo'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='tituloFrase',
            field=models.CharField(max_length=100),
        ),
    ]
