# Generated by Django 5.2 on 2025-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_frase_metodos_alter_frase_categoriafrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frase',
            name='modelo_laudo',
        ),
        migrations.AddField(
            model_name='frase',
            name='modelos_laudo',
            field=models.ManyToManyField(blank=True, to='api.modelolaudo'),
        ),
    ]
